
apiVersion: v1
kind: Service
metadata:
  name: minimal-app-v2
  namespace: demo
spec:
  selector:
    app: minimal-app-v2
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP