apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-app
  namespace: demo
spec:
  ingressClassName: nginx
  rules:
    - host: app.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minimal-app
                port:
                  number: 80

